### ISSUE TITLE
"0" prefixed PINs in HASS not accepted

### ISSUE THREAD

**Issue by alistairg** [postlund/pyatv#291]
**Describe the bug**

During the awesome new configuration flow in the beta component for apple_tv, I'm prompted for a series of PINs. The entry field is obviously expecting an integer, rather than a string, so cunningly deletes a "0" if the pin starts with one (e.g. 0123). This means pairing fails, and you have to keep retrying until Apple TV generates a new PIN.

**To Reproduce**

Try entering a PIN with a zero prefix, e.g. 0123. HASS will change it to "123" in the text field.

**Expected behavior**

I need to be able to enter 0123.

**System Setup (please complete the following information):**
 - OS: [e.g. Debian] Hass.io
 - Python: [e.g. 3.6.2] Hass.io
 - pyatv: [e.g. 0.3.10] Beta plugin via CACS

**Additional context**

**Comment by postlund** [comment]
Ah, yes, I can see how this is a problem. I'll make sure to fix it in the next release. Thanks for reporting!

**Comment by postlund** [comment]
This should be fixed now since I merged #299. Next time I make a new pre-release and update the component it will be possible to verify.

**Comment by postlund** [comment]
Fix was included in latest component update, so I will close this now.

**Comment by JesseWebDotCom** [comment]
Still getting this issue - just installed.  Pin code erases when the pin starts with a 0

**Comment by postlund** [comment]
@JesseWebDotCom Which protocol are you pairing?

**Comment by glassbase** [comment]
I think this is HA issue. Doesn’t accept leading zeros. 

Related - I just had this happen when repairing my PS4. PS4 provided a leading zero pin, it said “invalid user input” or something like that. Regenerated code (that didn’t start with 0) on PS4 and it worked. 

Could be wrong?

**Comment by postlund** [comment]
> I think this is HA issue. Doesn’t accept leading zeros.
> 
> Related - I just had this happen when repairing my PS4. PS4 provided a leading zero pin, it said “invalid user input” or something like that. Regenerated code (that didn’t start with 0) on PS4 and it worked.
> 
> Could be wrong?

When using an integer as input, there will be no leading zeros, of course. But `pyatv` compensates internally by padding with zeros, so it shouldn't be a problem.

**Comment by JesseWebDotCom** [comment]
> @JesseWebDotCom Which protocol are you pairing?

Just paired another Apple TV and the issue happened on the first passcode.  I started typing the leading 0 and the GUI erased it.  I was able to force enter the 0 eventually and it proceeded to the next pairing without issue.

**Comment by postlund** [comment]
I was able to reproduce this myself using the MRP proxy (that way I can specify pin myself). Will look into it tonight.

**Comment by postlund** [comment]
@JesseWebDotCom Ok, so it was PIN handling in proxy that was wrong. I corrected it so I could correctly pair with both the Remote app and Home Assistant using PIN code 1 (0001 in the app).

As stated earlier, the input dialog expects an integer and will remove leading zeros. That is fine. Did you get an actual error with the latest release (other than leading zeros being remove)? Any traces in the logs?

**Comment by JesseWebDotCom** [comment]
No actual error - the leading zeros got erased, I didn’t notice, and then pairing failed because the pin was obviously wrong.

**Comment by postlund** [comment]
Ok, so I guess this is not really a problem then? I have updated the description for that particular dialog to clarify that leading zeros should not be entered. Will be part of next update.

**Comment by postlund** [comment]
Ok, so I'm not sure we are talking about the same thing here? What I basically want to know: if the PIN code presented on screen has leading zeros, e.g. 0123, and you enter 123 (with no leading zero) in Home Assistant, do you get an error (red text in the dialog) or does it proceed to the next dialog?

As long as the usecase above works, then it is ok. The fact that you cannot enter leading zeros is usability disconvience, not an error.

**Comment by alistairg** [comment]
FYI - I was pairing with Apple TV this weekend and noticed two things - neither of which are "bugs", but both appear to be.

1. I was prompted with for a PIN with a leading zero. Although HASS deleted the leading zero (bug, not your fault), it did actually pair fine.
2. Apple TV didn't prompt me for an Airplay PIN, although HASS expected one. Turned out the issue here was that, as I'd deleted and recreated my HomeKit home, AppleTV wasn't associated with a room. In that case, there is no PIN prompt. 

Net/net - worked fine :)

**Comment by postlund** [comment]
@alistairg Thanks for reporting 😄 It sounds like it worked as expected. It's a balance act here since the data entry flow framework is pretty limited when it comes to input validation. I can do integer or strings which has both pros and cons. With integer it's not possible to input leading zeros, but it's at least an integer as input. If I change to use a string, then it is possible to input leading zeros, but you can also input "tacocat" or "monkey". So I have settled with integer and will write in the description that leading zeros shall be ignored. Good enough for now until better validation is possible.

Regarding 2), could you elaborate a bit more on that? I don't quite follow. There has been reports with other cases where the PIN would not show and I'm trying to keep track of those in the documentation, so I can point to that later on. Would love it if you would care to write a few lines about it to help other people out. The page is here:

https://github.com/postlund/pyatv/blob/master/docs/support/troubleshooting.md

If you don't feel like it, then I can do it if I get some additional details on the matter 👍

**Comment by postlund** [comment]
Based on the latest input I'm gonna close this again. A more proper fix (supporting integer with leading zeros) will have to be implemented once data entry flow supports better input validation.
