### ISSUE TITLE
Error returned when asking for status

### ISSUE THREAD

**Issue by oculist37** [postlund/pyatv#875]
**Describe the bug**
Hello,

I have an error when I try to get the status of the Apple TV : 
"WARNING: Received UpdateClientMessage for unknown player com.apple.TVHomeSharing
WARNING: Received UpdateClientMessage for unknown player com.apple.TVAirPlay"
But it works, since I have this after : "Media type: Video
Device state: Playing, etc"

It returns this error with "playing" and with "device_state"

Do I miss something ?

**System Setup (please complete the following information):**
 - OS: Mac OS Catalina
 - Python: 3.8.3
 - pyatv: 0.7.4
- Apple TV: Apple TV 4K tvOS 14.0

**Comment by postlund** [comment]
Normally the device will provide information about clients via `SetStateMessage`. Changes to the clients are then performed with `UpdateClientMessags`. In this case it seems like changes are made to a client which have not been announced yet. It's not bound to any specific function so it will happen at some point in time, when the device decides to make changes. There might seem to be patterns, but those are just coincidence.

I can try to debug this if you provide a debug log to me.

**Comment by oculist37** [comment]
Thanks for your answer,

I’m going to try something : repairing to see if it fixes the issue. If it works, I will tell you.

Otherwise, how can I give you a debug log ?

**Comment by postlund** [comment]
Sure, go nuts! 🥜 

The simplest way would be if it's reproducible with `atvremote`. Then you could just try `atvremote -s <ip to ATV> playing`. When doing it programmatically, you need to set up python logging and enable it for pyatv. Set up can be done like this:

https://github.com/postlund/pyatv/blob/046ff02f6c202835957cb11c80f0617ff068fc01/pyatv/scripts/atvremote.py#L449

Enabling log points should be:

```python
logging.getLogger("pyatv").setLevel(logging.DEBUG)
```

**Comment by ntindle** [comment]
I also got this issue on .118
Will try the command you listed

**Comment by oculist37** [comment]
Hi,

Sorry for the delay of my answer.

I tried to pair again because I had an issue after a system update of Catalina which broke pyatv and lot of errors. So, I’ve created an another virtual environment and reinstalled pyatv. And it worked again easily without pairing again. But I had this warning problem. I thought it may due to this bad former pairing, but even after another clean pairing, I always have the same error messages.

Now the other problem is I am a real beginner so I didn’t manage to activate the debug mode. If I understand what you mean, I have to change in the script atveremote.py something. I tried to add the line you gave me, I tried to replace the actual logger, but I didn’t succeed.

   logging.basicConfig(
        level=loglevel,
        datefmt="%Y-%m-%d %H:%M:%S",
        format="%(asctime)s %(levelname)s: %(message)s",
    )
    #logging.getLogger("requests").setLevel(logging.WARNING)
    logging.getLogger("pyatv").setLevel(logging.DEBUG)

What am I doing wrong ?

Thanks for your answers (no rush)

**Comment by danelewis** [comment]
Hi!

I'm having the same issue, new Home Assistant installation with Apple TV 4k running iOS 14.2, and using the beta Apple TV integration. Debug output below, Apple TV playing a video on Netflix when this was captured.
`atvremote -s 192.168.1.45 --debug playing
2020-11-22 01:40:06 DEBUG: Knocking at port 3689 on 192.168.1.45
2020-11-22 01:40:06 DEBUG: Knocking at port 7000 on 192.168.1.45
2020-11-22 01:40:06 DEBUG: Knocking at port 49152 on 192.168.1.45
2020-11-22 01:40:06 DEBUG: Knocking at port 32498 on 192.168.1.45
2020-11-22 01:40:06 DEBUG: Cleaning up after UDNS request
2020-11-22 01:40:06 DEBUG: Cleaning up after UDNS request
2020-11-22 01:40:06 DEBUG: Cleaning up after UDNS request
2020-11-22 01:40:06 DEBUG: Auto-discovered Living Room at 192.168.1.45:49153 (Protocol.MRP)
2020-11-22 01:40:06 DEBUG: Auto-discovered Living Room at 192.168.1.45:7000 (Protocol.AirPlay)
2020-11-22 01:40:06 INFO: Auto-discovered Living Room at 192.168.1.45
2020-11-22 01:40:06 DEBUG: No AirPlay credentials loaded
2020-11-22 01:40:06 DEBUG: Connection made to device
2020-11-22 01:40:06 DEBUG: Configured keep-alive on <asyncio.TransportSocket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.254', 57500), raddr=('192.168.1.45', 49153)> (Linux)
2020-11-22 01:40:06 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 Connection established
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 >> Send (Data=080f122444393534313537372d394534302d343537362d423735462d3342423143393942303430332000a20183010a2439333030646662622d363963622d343335662d393131612d383633636430333630323938120570796174761a066950686f6e6522063138413339332a12636f6d2e6170706c652e545652656d6f746532063334342e32383801404d480150016211636f6d2e6170706c652e54564d75736963680170017801880102a80101b00101)
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 >> Send: Protobuf: type: DEVICE_INFO_MESSAGE
identifier: "D9541577-9E40-4576-B75F-3BB1C99B0403"
errorCode: NoError
[deviceInfoMessage] {
  uniqueIdentifier: "9300dfbb-69cb-435f-911a-863cd0360298"
  name: "pyatv"
  localizedModelName: "iPhone"
  systemBuildVersion: "18A393"
  applicationBundleIdentifier: "com.apple.TVRemote"
  applicationBundleVersion: "344.28"
  protocolVersion: 1
  lastSupportedMessageType: 77
  supportsSystemPairing: true
  allowsPairing: true
  systemMediaApplication: "com.apple.TVMusic"
  supportsACL: true
  supportsSharedQueue: true
  supportsExtendedMotion: true
  sharedQueueVersion: 2
  deviceClass: iPhone
  logicalDeviceCount: 1
}
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 << Receive (Data=a203080f122444393534313537372d394534302d343537362d423735462d3342423143393942303430332000a201cd020a2430333430333839352d413838302d343142312d413237332d453139313133443538433733120b4c6976696e6720526f6f6d1a094170706c65c2a05456220531384b35372a16636f6d2e6170706c652e6d6564696172656d6f7465643801406a480150016211636f6d2e6170706c652e54564d757369636801700178018801029a012432373639463744322d343641372d344631412d423445322d434646463336413833463845a2011135303a64653a30363a37313a34343a6534a80104b00101c00100d201244532324633464...)
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 << Receive: Protobuf: type: DEVICE_INFO_MESSAGE
identifier: "D9541577-9E40-4576-B75F-3BB1C99B0403"
errorCode: NoError
[deviceInfoMessage] {
  uniqueIdentifier: "03403895-A880-41B1-A273-E19113D58C73"
  name: "Living Room"
  localizedModelName: "Apple\302\240TV"
  systemBuildVersion: "18K57"
  applicationBundleIdentifier: "com.apple.mediaremoted"
  protocolVersion: 1
  lastSupportedMessageType: 106
  supportsSystemPairing: true
  allowsPairing: true
  systemMediaApplication: "com.apple.TVMusic"
  supportsACL: true
  supportsSharedQueue: true
  supportsExtendedMotion: true
  sharedQueueVersion: 2
  deviceUID: "2769F7D2-46A7-4F1A-B4E2-CFFF36A83F8E"
  managedConfigDeviceID: "50:de:06:71:44:e4"
  deviceClass: AppleTV
  logicalDeviceCount: 1
  isProxyGroupPlayer: false
  groupUID: "E22F3FB2-6632-4FBA-917E-608DBAE4F921"
  isGroupLeader: true
  isAirplayActive: true
  systemPodcastApplication: "com.apple.podcasts"
  enderDefaultGroupUID: "E22F3FB2-6632-4FBA-917E-608DBAE4F921"
  airplayReceivers: "TVAirPlay"
  37: 0
  38: 1
  39: "AppleTV6,2"
}
85: "761942EA-5471-4FB6-AB22-29E9A6E33656"
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 >> Send (Data=08262000d202020802)
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 >> Send: Protobuf: type: SET_CONNECTION_STATE_MESSAGE
errorCode: NoError
[setConnectionStateMessage] {
  state: Connected
}
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 >> Send (Data=0810122445464435323045452d433237412d344344302d423139302d4132384336304543364345372000aa010a08011000180120012800)
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 >> Send: Protobuf: type: CLIENT_UPDATES_CONFIG_MESSAGE
identifier: "EFD520EE-C27A-4CD0-B190-A28C60EC6CE7"
errorCode: NoError
[clientUpdatesConfigMessage] {
  artworkUpdates: true
  nowPlayingUpdates: false
  volumeUpdates: true
  keyboardUpdates: true
  outputDeviceUpdates: false
}
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 << Receive (Data=a20108412000aa04740a380a0b4c6976696e6720526f6f6d122432373639463744322d343641372d344631412d423445322d4346464633364138334638455005a802001a380a0b4c6976696e6720526f6f6d122432373639463744322d343641372d344631412d423445322d4346464633364138334638455005a80200aa052441443939334532442d423434462d343336352d413445322d413545353743433230413638a70508482000da04f80412c9040a04080110010a04083a10010acf0108301001880107880103880106880102880105880101880108920123636f6d2e6170706c652e6d757369632e706c61796261636b71756575652e726164696...)
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 << Receive: Protobuf: type: UPDATE_OUTPUT_DEVICE_MESSAGE
errorCode: NoError
[updateOutputDeviceMessage] {
  outputDevices {
    name: "Living Room"
    uniqueIdentifier: "2769F7D2-46A7-4F1A-B4E2-CFFF36A83F8E"
    deviceType: Wired
    volumeCapabilities: 0
  }
  3 {
    1: "Living Room"
    2: "2769F7D2-46A7-4F1A-B4E2-CFFF36A83F8E"
    10: 5
    37: 0
  }
}
85: "AD993E2D-B44F-4365-A4E2-A5E57CC20A68"
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 << Receive: Protobuf: type: SET_DEFAULT_SUPPORTED_COMMANDS_MESSAGE
errorCode: NoError
[setDefaultSupportedCommandsMessage] {
  supportedCommands {
    supportedCommands {
      command: Play
      enabled: true
    }
    supportedCommands {
      command: PrepareForSetQueue
      enabled: true
    }
    supportedCommands {
      command: SetPlaybackQueue
      enabled: true
      supportedPlaybackQueueTypes: 7
      supportedPlaybackQueueTypes: 3
      supportedPlaybackQueueTypes: 6
      supportedPlaybackQueueTypes: 2
      supportedPlaybackQueueTypes: 5
      supportedPlaybackQueueTypes: 1
      supportedPlaybackQueueTypes: 8
      supportedCustomQueueIdentifiers: "com.apple.music.playbackqueue.radio"
      supportedCustomQueueIdentifiers: "com.apple.music.playbackqueue.tracklist"
      supportedCustomQueueIdentifiers: "com.apple.MediaPlaybackCore.playbackContextArchive-v1.opack"
      supportedCustomQueueIdentifiers: "com.apple.mediaplayer.playbackcontext"
    }
    supportedCommands {
      command: SetPlaybackSession
      enabled: true
      supportedPlaybackSessionTypes: "com.apple.MediaPlaybackCore.playbackSession-v4.opack:subscription:cloudLibrary:9142986"
      supportedPlaybackSessionTypes: "com.apple.MediaPlaybackCore.playbackSession-v3.opack:subscription:cloudLibrary:9142986"
      supportedPlaybackSessionTypes: "com.apple.MediaPlaybackCore.playbackSession-v4.opack:subscription:cloudLibrary:8c11834"
      supportedPlaybackSessionTypes: "com.apple.MediaPlaybackCore.playbackSession-v3.opack:subscription:cloudLibrary:8c11834"
    }
  }
  displayID: "com.apple.TVMusic"
  8 {
  }
  9 {
    2 {
      2: "com.apple.TVMusic"
    }
  }
}
85: "29CBE3DD-63BC-429D-89B6-928BA8D64542"
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 << Receive: Protobuf: type: SET_DEFAULT_SUPPORTED_COMMANDS_MESSAGE
errorCode: NoError
[setDefaultSupportedCommandsMessage] {
  supportedCommands {
    supportedCommands {
      command: Play
      enabled: true
    }
    supportedCommands {
      command: SetPlaybackQueue
      enabled: true
      supportedPlaybackQueueTypes: 3
      supportedPlaybackQueueTypes: 6
      supportedPlaybackQueueTypes: 2
      supportedPlaybackQueueTypes: 5
      supportedPlaybackQueueTypes: 1
    }
    supportedCommands {
      command: SetPlaybackSession
      enabled: true
      supportedPlaybackSessionTypes: "com.apple.podcasts.MTPlaybackQueueController.GenericQueue"
      currentPlaybackSessionTypes: "com.apple.podcasts.MTPlaybackQueueController.GenericQueue"
    }
  }
  displayID: "com.apple.podcasts"
  8 {
  }
  9 {
    2 {
      2: "com.apple.podcasts"
    }
  }
}
85: "55623FFB-9FB8-470C-87C4-D007147BFB5E"
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 << Receive: Protobuf: type: SET_NOW_PLAYING_CLIENT_MESSAGE
errorCode: NoError
[setNowPlayingClientMessage] {
  client {
    processIdentifier: 181
    bundleIdentifier: "com.apple.TVAirPlay"
  }
}
85: "AFA22B99-A28B-4F25-9FC2-A36A2BC755D8"
2020-11-22 01:40:07 DEBUG: Dispatching message with type 46 (SetNowPlayingClientMessage) to Listener(func=<bound method PlayerStateManager._handle_set_now_playing_client of <pyatv.mrp.player_state.PlayerStateManager object at 0x7fc7c95c48e0>>, data=None)
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 << Receive: Protobuf: type: UPDATE_CLIENT_MESSAGE
errorCode: NoError
[updateClientMessage] {
  client {
    processIdentifier: 181
    bundleIdentifier: "com.apple.TVAirPlay"
    processUserIdentifier: 501
    displayName: "AirPlay"
  }
}
85: "46590413-CA98-43B8-B990-DA05E3D09724"
2020-11-22 01:40:07 DEBUG: Dispatching message with type 55 (UpdateClientMessage) to Listener(func=<bound method PlayerStateManager._handle_update_client of <pyatv.mrp.player_state.PlayerStateManager object at 0x7fc7c95c48e0>>, data=None)
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 << Receive: Protobuf: type: SET_STATE_MESSAGE
errorCode: NoError
[setStateMessage] {
  supportedCommands {
    supportedCommands {
      command: Play
      enabled: true
    }
    supportedCommands {
      command: Pause
      enabled: true
    }
    supportedCommands {
      command: TogglePlayPause
      enabled: true
    }
    supportedCommands {
      command: Stop
      enabled: true
    }
    supportedCommands {
      command: NextTrack
      enabled: true
    }
    supportedCommands {
      command: PreviousTrack
      enabled: true
    }
    supportedCommands {
      command: BeginFastForward
      enabled: true
    }
    supportedCommands {
      command: EndFastForward
      enabled: true
    }
    supportedCommands {
      command: BeginRewind
      enabled: true
    }
    supportedCommands {
      command: EndRewind
      enabled: true
    }
    supportedCommands {
      command: AdvanceRepeatMode
      enabled: true
    }
    supportedCommands {
      command: AdvanceShuffleMode
      enabled: true
    }
    supportedCommands {
      command: SeekToPlaybackPosition
      enabled: true
    }
  }
  playbackQueue {
    location: 0
    contentItems {
      identifier: "69410E3F-36F6-449D-A16B-5CA60341A2B3"
    }
  }
  displayName: "AirPlay"
  playbackState: Paused
  playbackQueueCapabilities {
    requestByRange: true
    requestByIdentifiers: true
  }
  playerPath {
    origin {
      displayName: "Living Room"
      identifier: 1280262988
    }
    client {
      processIdentifier: 181
      bundleIdentifier: "com.apple.TVAirPlay"
    }
    player {
      identifier: "MediaRemote-DefaultPlayer"
      displayName: "Default Player"
    }
  }
  playbackStateTimestamp: 627202740.412417
}
85: "7BD8A823-D751-4B9E-9972-680761FF5565"
2020-11-22 01:40:07 DEBUG: Dispatching message with type 4 (SetStateMessage) to Listener(func=<bound method PlayerStateManager._handle_set_state of <pyatv.mrp.player_state.PlayerStateManager object at 0x7fc7c95c48e0>>, data=None)
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 << Receive: Protobuf: type: UPDATE_CLIENT_MESSAGE
errorCode: NoError
[updateClientMessage] {
  client {
    processIdentifier: 1059
    bundleIdentifier: "au.net.abc.ABCiView"
    processUserIdentifier: 501
    displayName: "ABC iview"
  }
}
85: "B29AEA50-1B7D-4EF2-9C2B-6C32B4E14D48"
2020-11-22 01:40:07 DEBUG: Dispatching message with type 55 (UpdateClientMessage) to Listener(func=<bound method PlayerStateManager._handle_update_client of <pyatv.mrp.player_state.PlayerStateManager object at 0x7fc7c95c48e0>>, data=None)
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 << Receive: Protobuf: type: SET_NOT_PLAYING_PLAYER_MESSAGE
errorCode: NoError
[setNowPlayingPlayerMessage] {
  playerPath {
    origin {
      displayName: "Living Room"
      identifier: 1280262988
    }
    client {
      processIdentifier: 1059
      bundleIdentifier: "au.net.abc.ABCiView"
    }
    player {
      identifier: "avkit-7B5D1AB6-96C8-4E5E-8988-A9949FCA49E5"
      displayName: "player-1"
    }
  }
}
85: "D5BA0468-641E-4065-B87F-57D29D4784EA"
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 << Receive: Protobuf: type: SET_STATE_MESSAGE
errorCode: NoError
[setStateMessage] {
  displayName: "ABC iview"
  playbackState: Paused
  playbackQueueCapabilities {
  }
  playerPath {
    origin {
      displayName: "Living Room"
      identifier: 1280262988
    }
    client {
      processIdentifier: 1059
      bundleIdentifier: "au.net.abc.ABCiView"
    }
    player {
      identifier: "MediaRemote-DefaultPlayer"
      displayName: "Default Player"
    }
  }
  playbackStateTimestamp: 627660430.701241
}
85: "97B3EEB8-3EE2-44AD-9B0F-BA9173B16C57"
2020-11-22 01:40:07 DEBUG: Dispatching message with type 4 (SetStateMessage) to Listener(func=<bound method PlayerStateManager._handle_set_state of <pyatv.mrp.player_state.PlayerStateManager object at 0x7fc7c95c48e0>>, data=None)
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 << Receive: Protobuf: type: SET_STATE_MESSAGE
errorCode: NoError
[setStateMessage] {
  playbackQueue {
    location: 0
    contentItems {
      identifier: "com.apple.avkit.1059.da96a973"
      metadata {
        title: "Staged - Series 1 Episode 1 Cachu Hwch"
        duration: 1331.046
        artworkAvailable: true
        infoAvailable: true
        languageOptionsAvailable: true
        numberOfSections: 0
        elapsedTime: 629.149233599
        isAlwaysLive: false
        playbackRate: 1.0
        contentIdentifier: "ZW2452A001S00"
        mediaType: Video
        nowPlayingInfoData: "bplist00\324\001\002\003\004\005\006\007\nX$versionY$archiverT$topX$objects\022\000\001\206\240_\020\017NSKeyedArchive...
        elapsedTimeTimestamp: 627662016.500338
        inferredTimestamp: 627660446.394222
        legacyUniqueIdentifier: -627660429
      }
      availableLanguageOptions {
        allowEmptySelection: false
        languageOptions {
          type: 0
          characteristics: "public.main-program-content"
          displayName: "Unknown"
          identifier: "--Unknown"
        }
      }
      availableLanguageOptions {
        allowEmptySelection: true
        languageOptions {
          type: 1
          languageTag: "__AUTO__"
        }
        languageOptions {
          type: 1
          languageTag: "en"
          characteristics: "public.main-program-content"
          displayName: "English"
          identifier: "English-en-English"
        }
      }
      currentLanguageOptions {
        type: 0
        characteristics: "public.main-program-content"
        displayName: "Unknown"
        identifier: "--Unknown"
      }
      currentLanguageOptions {
        type: 1
        languageTag: "en"
        characteristics: "public.main-program-content"
        displayName: "English"
        identifier: "English-en-English"
      }
    }
    requestId: "PlaybackQueueInvalidation-9777D2A1-3A66-493C-AF3F-E365728E9CAE"
    resolvedPlayerPath {
      origin {
        displayName: "Living Room"
        identifier: 1280262988
      }
      client {
        processIdentifier: 1059
        bundleIdentifier: "au.net.abc.ABCiView"
      }
      player {
        identifier: "avkit-7B5D1AB6-96C8-4E5E-8988-A9949FCA49E5"
        displayName: "player-1"
        5: 4548370366642
      }
    }
  }
  displayName: "ABC iview"
  playbackState: Playing
  playbackQueueCapabilities {
    requestByRange: true
  }
  playerPath {
    origin {
      displayName: "Living Room"
      identifier: 1280262988
    }
    client {
      processIdentifier: 1059
      bundleIdentifier: "au.net.abc.ABCiView"
    }
    player {
      identifier: "avkit-7B5D1AB6-96C8-4E5E-8988-A9949FCA49E5"
      displayName: "player-1"
    }
  }
  playbackStateTimestamp: 627661378.933252
}
85: "0E04550E-A27E-432D-8D2E-AD5A5B672B96"
2020-11-22 01:40:07 DEBUG: Dispatching message with type 4 (SetStateMessage) to Listener(func=<bound method PlayerStateManager._handle_set_state of <pyatv.mrp.player_state.PlayerStateManager object at 0x7fc7c95c48e0>>, data=None)
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 << Receive: Protobuf: errorCode: NoError
62 {
  1 {
    1 {
      2: "Living Room"
      3: 1280262988
    }
    2 {
      1: 1059
      2: "au.net.abc.ABCiView"
    }
    3 {
      1: "avkit-7B5D1AB6-96C8-4E5E-8988-A9949FCA49E5"
      2: "player-1"
      5: 4548370366642
    }
  }
}
85: "28AD2007-7798-4C5C-8600-8C830A22FA82"
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 << Receive: Protobuf: type: UPDATE_CLIENT_MESSAGE
errorCode: NoError
[updateClientMessage] {
  client {
    processIdentifier: 1064
    bundleIdentifier: "com.netflix.Netflix"
    processUserIdentifier: 501
    displayName: "Netflix"
  }
}
85: "01B545FA-3292-4662-9547-FFEFCF564456"
2020-11-22 01:40:07 DEBUG: Dispatching message with type 55 (UpdateClientMessage) to Listener(func=<bound method PlayerStateManager._handle_update_client of <pyatv.mrp.player_state.PlayerStateManager object at 0x7fc7c95c48e0>>, data=None)
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 << Receive: Protobuf: type: SET_NOT_PLAYING_PLAYER_MESSAGE
errorCode: NoError
[setNowPlayingPlayerMessage] {
  playerPath {
    origin {
      displayName: "Living Room"
      identifier: 1280262988
    }
    client {
      processIdentifier: 1064
      bundleIdentifier: "com.netflix.Netflix"
    }
    player {
      identifier: "avkit-74A8B57C-AB03-456C-AE24-D376B291B8F3"
      displayName: "player-1"
    }
  }
}
85: "6944B112-A032-4F7C-8208-53F9338EC111"
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 << Receive: Protobuf: type: SET_STATE_MESSAGE
errorCode: NoError
[setStateMessage] {
  displayName: "Netflix"
  playbackState: Paused
  playbackQueueCapabilities {
  }
  playerPath {
    origin {
      displayName: "Living Room"
      identifier: 1280262988
    }
    client {
      processIdentifier: 1064
      bundleIdentifier: "com.netflix.Netflix"
    }
    player {
      identifier: "MediaRemote-DefaultPlayer"
      displayName: "Default Player"
    }
  }
  playbackStateTimestamp: 627662172.947669
}
85: "C9F11F88-9569-43BB-A6DC-64E8637E74D6"
2020-11-22 01:40:07 DEBUG: Dispatching message with type 4 (SetStateMessage) to Listener(func=<bound method PlayerStateManager._handle_set_state of <pyatv.mrp.player_state.PlayerStateManager object at 0x7fc7c95c48e0>>, data=None)
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 << Receive: Protobuf: type: SET_STATE_MESSAGE
errorCode: NoError
[setStateMessage] {
  supportedCommands {
    supportedCommands {
      command: Play
      enabled: true
    }
    supportedCommands {
      command: Pause
      enabled: true
    }
    supportedCommands {
      command: TogglePlayPause
      enabled: true
    }
    supportedCommands {
      command: EnableLanguageOption
      enabled: true
    }
    supportedCommands {
      command: DisableLanguageOption
      enabled: true
    }
    supportedCommands {
      command: Stop
      enabled: true
    }
    supportedCommands {
      command: SkipForward
      enabled: true
      preferredIntervals: 10.0
    }
    supportedCommands {
      command: SkipBackward
      enabled: true
      preferredIntervals: 10.0
    }
    supportedCommands {
      command: BeginFastForward
      enabled: true
    }
    supportedCommands {
      command: BeginRewind
      enabled: true
    }
    supportedCommands {
      command: ChangePlaybackRate
      enabled: true
    }
    supportedCommands {
      command: SeekToPlaybackPosition
      enabled: true
      canScrub: 0
    }
    supportedCommands {
      command: NextInContext
      enabled: true
    }
    supportedCommands {
      command: PreviousInContext
      enabled: true
    }
  }
  playbackQueue {
    location: 0
    contentItems {
      identifier: "com.apple.avkit.1064.da96a2a3"
      metadata {
        title: "S3: E2 \"Elephants and Hens\""
        duration: 1447.198
        artworkAvailable: true
        infoAvailable: true
        languageOptionsAvailable: true
        numberOfSections: 0
        elapsedTime: 732.636260708
        isAlwaysLive: false
        playbackRate: 1.0
        mediaType: Video
        nowPlayingInfoData: "bplist00\324\001\002\003\004\005\006\007\nX$versionY$archiverT$topX$objects\022\000\001\206\240_\020\017NSKeyedArchive...
        elapsedTimeTimestamp: 627662173.450989
        inferredTimestamp: 627662172.945052
        legacyUniqueIdentifier: -627662173
      }
      availableLanguageOptions {
        allowEmptySelection: false
        languageOptions {
          type: 0
          languageTag: "en"
          characteristics: "public.main-program-content"
          displayName: "English"
          identifier: "English [Original]-en-English"
        }
      }
      availableLanguageOptions {
        allowEmptySelection: true
        languageOptions {
          type: 1
          languageTag: "__AUTO__"
        }
        languageOptions {
          type: 1
          languageTag: "en"
          characteristics: "public.main-program-content"
          characteristics: "public.accessibility.transcribes-spoken-dialog"
          characteristics: "public.accessibility.describes-music-and-sound"
          displayName: "English SDH"
          identifier: "English-en-English SDH"
        }
      }
      currentLanguageOptions {
        type: 0
        languageTag: "en"
        characteristics: "public.main-program-content"
        displayName: "English"
        identifier: "English [Original]-en-English"
      }
    }
    requestId: "PlaybackQueueInvalidation-AD2EE8FC-BEE5-400E-93D6-13B6B8C01860"
    resolvedPlayerPath {
      origin {
        displayName: "Living Room"
        identifier: 1280262988
      }
      client {
        processIdentifier: 1064
        bundleIdentifier: "com.netflix.Netflix"
      }
      player {
        identifier: "avkit-74A8B57C-AB03-456C-AE24-D376B291B8F3"
        displayName: "player-1"
        5: 4569845203129
      }
    }
  }
  displayName: "Netflix"
  playbackState: Playing
  playbackQueueCapabilities {
    requestByRange: true
  }
  playerPath {
    origin {
      displayName: "Living Room"
      identifier: 1280262988
    }
    client {
      processIdentifier: 1064
      bundleIdentifier: "com.netflix.Netflix"
    }
    player {
      identifier: "avkit-74A8B57C-AB03-456C-AE24-D376B291B8F3"
      displayName: "player-1"
    }
  }
  playbackStateTimestamp: 627662172.963028
}
85: "0EB78AFE-BB3E-4C3A-BD13-9F876832FC7A"
2020-11-22 01:40:07 DEBUG: Dispatching message with type 4 (SetStateMessage) to Listener(func=<bound method PlayerStateManager._handle_set_state of <pyatv.mrp.player_state.PlayerStateManager object at 0x7fc7c95c48e0>>, data=None)
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 << Receive: Protobuf: errorCode: NoError
62 {
  1 {
    1 {
      2: "Living Room"
      3: 1280262988
    }
    2 {
      1: 1064
      2: "com.netflix.Netflix"
    }
    3 {
      1: "avkit-74A8B57C-AB03-456C-AE24-D376B291B8F3"
      2: "player-1"
      5: 4569845203129
    }
  }
}
85: "53339AC3-9602-4479-8BAC-A3267661AD54"
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 << Receive: Protobuf: type: UNKNOWN_MESSAGE
identifier: "EFD520EE-C27A-4CD0-B190-A28C60EC6CE7"
errorCode: NoError
85: "2E4E22E9-877E-47C2-BE02-11488E6D3C0A"
2020-11-22 01:40:07 DEBUG: Active player is now com.apple.TVAirPlay
2020-11-22 01:40:07 WARNING: Received UpdateClientMessage for unknown player com.apple.TVAirPlay
2020-11-22 01:40:07 WARNING: Received UpdateClientMessage for unknown player au.net.abc.ABCiView
2020-11-22 01:40:07 WARNING: Received UpdateClientMessage for unknown player com.netflix.Netflix
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 >> Send (Data=0818122432343536443742342d313839332d343235432d383538412d4233373030364630464130302000)
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 >> Send: Protobuf: type: GET_KEYBOARD_SESSION_MESSAGE
identifier: "2456D7B4-1893-425C-858A-B37006F0FA00"
errorCode: NoError
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 << Receive (Data=680817122432343536443742342d313839332d343235432d383538412d4233373030364630464130302000e2011408001a101a0e0800100018003000380040004800aa052442433144373538332d414132342d343731442d423338382d333031414642443345443341)
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 << Receive: Protobuf: type: KEYBOARD_MESSAGE
identifier: "2456D7B4-1893-425C-858A-B37006F0FA00"
errorCode: NoError
[keyboardMessage] {
  state: 0
  attributes {
    inputTraits {
      autocapitalizationType: NONE
      keyboardType: KEYBOARD_TYPE_DEFAULT
      returnKeyType: RETURN_KEY_DEFAULT
      enablesReturnKeyAutomatically: false
      secureTextEntry: false
      validTextRangeLocation: 0
      validTextRangeLength: 0
    }
  }
}
85: "BC1D7583-AA24-471D-B388-301AFBD3ED3A"
  Media type: Unknown
Device state: Paused
      Repeat: Off
     Shuffle: Off
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 Closing connection
2020-11-22 01:40:07 DEBUG: 192.168.1.254:57500<->192.168.1.45:49153 Disconnected from device: None`

**Comment by postlund** [comment]
@danelewis That's exactly what I need, thank you! I will not have time to look at this today, but maybe tomorrow.

@oculist37 Got what I needed from @danelewis  👍

**Comment by oculist37** [comment]
Hi,

Just in case, I send you my debug log.

Have a nice day

**Comment by RefineryX** [comment]
Also having the same issue. Happy to help with sending debugs if helpful.

**Comment by oculist37** [comment]
Hi again,

Another small issue. The Apple TV is often not found at the first time. Here’s the log.

(pyatv_venvi) mac-mini-de-secretariat:~ jeremiehalfon$ atvremote --id 6C:4A:85:13:EC:3E playing
2020-11-25 16:04:29 ERROR: Could not find any Apple TV on current network
(pyatv_venvi) mac-mini-de-secretariat:~ jeremiehalfon$ atvremote --id 6C:4A:85:13:EC:3E playing
2020-11-25 16:04:38 WARNING: Received UpdateClientMessage for unknown player com.apple.TVMusic
2020-11-25 16:04:38 WARNING: Received UpdateClientMessage for unknown player com.apple.TVAirPlay
2020-11-25 16:04:38 WARNING: Received UpdateClientMessage for unknown player com.apple.TVHomeSharing
  Media type: Video
Device state: Playing


As you can see, when I ask the same command few seconds after, it works.

**Comment by postlund** [comment]
I pushed a fix to #880, please try it out. That scanning is unreliable is unrelated to this and very well known, there are a bunch of issues about it.

**Comment by oculist37** [comment]
Hi,

It still doesn’t work, but I don’t know if I’ve managed to install properly your fix.

I enter : pip3 install git+https://github.com/postlund/pyatv.git@refs/pull/880/head <git+https://github.com/postlund/pyatv.git@refs/pull/880/head>

I have this message WARNING: Did not find branch or tag 'refs/pull/880/head', assuming revision or ref

But after I have : Successfully built pyatv

**Comment by oculist37** [comment]
And for that issue, isn’t it possible to add in the atvremote script just one loop : if apple TV is not found, ask again just one more time. If it’s found : ok continue the script, otherwise return Could not find any Apple TV on current network


I know it’s easy to say but surely not so easy to do.

**Comment by postlund** [comment]
@oculist37 I would expect that you didn't get the correct version. Not sure why that command wouldn't work, but maybe you can clone the repo, check out the branch and install manually?

Also, adding a loop in `atvremote` is fine but not something with priority from my end. It is meant as a reference tool to try out the library and that kind of logic would be subject to the user to implement. When I decide to add support for continuous scanning (#293), `atvremote` can be made to wait indefinitely for the device to show up.

**Comment by postlund** [comment]
@oculist37 I can easily verify it myself, so I will merge the PR and call it a day! Will be part of the next release.

**Comment by oculist37** [comment]
Hi,

Your v0.7.5 works just fine !

Thanks again and have a nice day
